name: book
channels:
  - conda-forge
  - defaults
dependencies:
  - control
  - slycot
  - scipy
  - sympy
  - ipympl
  - ipython
  - jupyter-book
  - jupyterlab
  - jupytext
  - numpy
  - pandas
  - pip
  - python=3.12
  - matplotlib
  - myst-nb
  - myst-parser
  - pip:
    - jupyterlab-myst

  
